### ISSUE TITLE
Is PGI a suported compiler?

### ISSUE THREAD

**Issue by dkokron** [NVIDIA/nccl-tests#38] opened 2020-02-27 18:55 UTC
make  MPI=1 MPI_HOME=/nasa/hpcx/2.5.0/ompi-pgi PREFIX=/nobackupp16/swbuild/dkokron/cuda/nccl-tests/install CUDA_HOME=/nasa/cuda/10.2 NVCC_GENCODE="-gencode=arch=compute_70,code=sm_70" NCCL_HOME=/nobackupp16/swbuild/dkokron/cuda/nccl/build
 src buildmake -C src build
make[1]: Entering directory '/nobackupp16/swbuild/dkokron/cuda/nccl-tests/src'
Compiling  all_reduce.cu                       > ../build/all_reduce.o
/nasa/pgi/19.10/linux86-64-llvm/19.10/include/edg/xmmintrin.h(2514): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r440/TC440_70/drivers/compiler/edg/EDG_5.0/src/sys_predef.c", line 574

1 catastrophic error detected in the compilation of "/tmp/pbs.8178378.pbspl1.nas.nasa.gov/tmpxft_00005bae_00000000-4_all_reduce.cpp4.ii".
Compilation aborted.
nvcc error   : 'cudafe++' died due to signal 6

**Comment by dkolsen-pgi** [comment] 2020-02-28 00:28
PGI is a supported host compiler for NVCC.  However, there is a bug in the integration between PGI 19.x and NVCC 10.2 when using x86 intrinsics, such as `<xmmintrin.h>`.  Some possible workarounds might be using a different version of PGI or NVCC, or moving the x86 intrinsics code to a separate .cpp file that is compiled with pgc++ rather than nvcc.

**Comment by sjeaugey** [comment] 2020-02-28 01:02
I'm not sure why we end up using xmm intrinsics inside the CUDA kernel code. Could it be caused by calls to memcpy ?
Can you try applying this patch to see if it fixes the compilation :
```
diff --git a/src/collectives/device/prims_ll.h b/src/collectives/device/prims_ll.h
index 4d5e0ce1..a3aa36ed 100644
--- a/src/collectives/device/prims_ll.h
+++ b/src/collectives/device/prims_ll.h
@@ -114,13 +114,11 @@ class ncclLLPrimitives {
 
   // Using memcpy handles misaligned pointers.
   __device__ uint64_t readAL(uint64_t* src) {
-    uint64_t val;
-    memcpy((char*)&val, (char*)src, sizeof(uint64_t));
-    return val;
+    return src[0];
   }
 
   __device__ void storeAL(uint64_t* dst, uint64_t val, uint32_t nbytes) {
-    memcpy((char*)dst, (char*)&val, nbytes);
+    dst[0] = val;
   }
 
   template <int RECV, int SEND, int SRC, int DST>
```

**Comment by dkokron** [comment] 2020-02-28 03:36
Thanks for the feedback.  I'll try the patch tomorrow and report back.
Dan

**Comment by AddyLaddy** [comment] 2021-07-07 17:03
No recent feedback so closing. Please open another one if you are still seeing issues.

**Closed by AddyLaddy** 2021-07-07 17:03 UTC
