### ISSUE TITLE
all_reduce_perf hangs; using a single GPU on a 4GPU machine

### ISSUE THREAD

**Issue by isaacgerg** [NVIDIA/nccl-tests#217] opened 2024-05-22 15:57 UTC
Downloaded, built, and installed NCCL and NCCL-tests today.  When I attempt to run on my Linux machine which contains 4 GPUs, the test hangs, even when running with a single GPU.  Below is an example output that I get after setting some debug flags in an attempt to diagnose.

```
:~/nccl-tests$ ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1
# nThread 1 nGpus 1 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 va                                                                                                                                  lidation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid  69438 on NAME device  0 [0x01] NVIDIA RTX A6000
NAME :69438:69438 [0] NCCL INFO Bootstrap : Using enp3s0f0:10.50.56.33<0>
NAME :69438:69438 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
NAME :69438:69438 [0] NCCL INFO NET/Plugin: Using internal network plugin.
NAME :69438:69438 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.21.5+cuda12.4
NAME :69438:69444 [0] NCCL INFO NET/IB : No device found.
NAME :69438:69444 [0] NCCL INFO NET/Socket : Using [0]enp3s0f0:10.50.56.33<0> [1]br-50a6a39f12ff:172.1                                                                                                                                  8.0.1<0> [2]br-93ef2f1539c5:172.25.0.1<0>
NAME :69438:69444 [0] NCCL INFO Using non-device net plugin version 0
NAME :69438:69444 [0] NCCL INFO Using network Socket

NAME :69438:69443 [0] misc/socket.cc:50 NCCL WARN socketProgress: Connection closed by remote peer NAME<59364>
NAME :69438:69443 [0] NCCL INFO misc/socket.cc:752 -> 6
NAME :69438:69443 [0] NCCL INFO misc/socket.cc:428 -> 6
NAME :69438:69443 [0] NCCL INFO misc/socket.cc:564 -> 6
NAME :69438:69443 [0] NCCL INFO misc/socket.cc:668 -> 6
NAME :69438:69443 [0] NCCL INFO bootstrap.cc:129 -> 6
```

I have provided the topology of the system  below:
```
:~$ nvidia-smi topo -m
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     0-63    0               N/A
GPU1    SYS      X      SYS     SYS     0-63    0               N/A
GPU2    SYS     SYS      X      SYS     0-63    0               N/A
GPU3    SYS     SYS     SYS      X      0-63    0               N/A

```

NVIDIA-SMI gives me the following below:
```
:~/nccl-tests$ nvidia-smi
Wed May 22 11:59:25 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A6000               Off |   00000000:01:00.0 Off |                  Off |
| 30%   31C    P8             26W /  300W |       3MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A6000               Off |   00000000:41:00.0 Off |                  Off |
| 30%   29C    P8             20W /  300W |       3MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA RTX A6000               Off |   00000000:81:00.0 Off |                  Off |
| 30%   29C    P8             22W /  300W |       3MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA RTX A6000               Off |   00000000:C1:00.0 Off |                  Off |
| 30%   28C    P8             16W /  300W |       3MiB /  49140MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+


```

**Comment by sjeaugey** [comment] 2024-05-22 16:03
You're running on a single GPU, so I'm not sure what you're trying to do, but it looks like the NIC enp3s0f0 is not letting NCCL communicate. If you don't intend to run on across multiple nodes, maybe try setting `NCCL_SOCKET_IFNAME=lo`?

**Comment by isaacgerg** [comment] 2024-05-22 16:08
@sjeaugey My intent was to demonstrate that even on a single GPU, the test hangs.  It hangs with more than 1 GPU specified also.

I tried your suggestion and it still hangs.  Here is the output:

```
:~/nccl-tests$ export NCCL_SOCKET_IFNAME=lo
:~/nccl-tests$ ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1
# nThread 1 nGpus 1 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
#  Rank  0 Group  0 Pid  70918 on NAME device  0 [0x01] NVIDIA RTX A6000
NAME :70918:70918 [0] NCCL INFO Bootstrap : Using lo:127.0.0.1<0>
NAME :70918:70918 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
NAME :70918:70918 [0] NCCL INFO NET/Plugin: Using internal network plugin.
NAME :70918:70918 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.21.5+cuda12.4
NAME :70918:70928 [0] NCCL INFO NET/IB : No device found.
NAME :70918:70928 [0] NCCL INFO NET/Socket : Using [0]lo:127.0.0.1<0>
NAME :70918:70928 [0] NCCL INFO Using non-device net plugin version 0
NAME :70918:70928 [0] NCCL INFO Using network Socket

NAME :70918:70927 [0] misc/socket.cc:50 NCCL WARN socketProgress: Connection closed by remote peer localhost<56086>
NAME :70918:70927 [0] NCCL INFO misc/socket.cc:752 -> 6
NAME:70918:70927 [0] NCCL INFO misc/socket.cc:428 -> 6
NAME :70918:70927 [0] NCCL INFO misc/socket.cc:564 -> 6
NAME :70918:70927 [0] NCCL INFO misc/socket.cc:668 -> 6
NAME :70918:70927 [0] NCCL INFO bootstrap.cc:129 -> 6
```

**Comment by sjeaugey** [comment] 2024-05-22 16:11
Alright, understood.

Would you have a very aggressive firewall that would prevent any network communication even through `lo`?

**Comment by isaacgerg** [comment] 2024-05-22 16:17
@sjeaugey We have no firewall on the machine.

**Comment by kiskra-nvidia** [comment] 2024-05-22 16:41
Mysterious... Given that it's reproducible within a single process, I would run all_reduce_perf under `strace -f` to get some insight what might be going on with these socket operations... Brace yourself for _a lot_ of output...

**Comment by kiskra-nvidia** [comment] 2024-05-22 17:08
The excerpt you attached are just after-effects (the thread is busy looking up the hostname to include in the debug output); the culprit must be earlier... You may want to attach the whole thing just to be sure (GitHub has a semi-hidden "Paste, drop, or click to add files" button underneath the comment box).

**Comment by isaacgerg** [comment] 2024-05-22 17:18
@kiskra-nvidia 

The log was too large to upload so I truncated it near where it started to repeat.  

[log_snip.txt](https://github.com/NVIDIA/nccl-tests/files/15406641/log_snip.txt)

**Comment by kiskra-nvidia** [comment] 2024-05-22 22:24
The first 8% or so of that log would've been enough 😄.

Still, it's very weird. It looks like a message just disappears?! I'm wondering if your node has its TCP/IP stack configured in some unusual (broken?) way. Can you try compiling (`gcc -pthread -o cs cs.c`) and running the attached source?
[cs.c.txt](https://github.com/NVIDIA/nccl-tests/files/15409231/cs.c.txt)
It should generate output such as this:
```
Server listening...
Client calling connect
Client calling send
Client calling shutdown
Client calling close
Client calling pthread_join...
Server calling accept...
Server calling recv...
Terminating the server
Terminating the client
```
but I'm curious if on your system it will trigger an assertion failure in line 39...

**Comment by kiskra-nvidia** [comment] 2024-05-23 15:15
As I suspected. For some reason, on your system, when a client sends a message to the server over a newly established TCP connection and then closes the connection before the server even accepts the connection, the message just disappears. That's rather unexpected and frankly it strikes me as broken, but at least it fails consistently so hopefully we can get to the bottom of this.

First, what distro is this? Are you running a distro kernel (and what version?) or something custom? Anything you can think of regarding any tweaks to the networking stack? In particular, any customizations to `/etc/sysctl.conf` / `/etc/sysctl.d/*` or the kernel command line (`cat /proc/cmdline`)? Let's double-check on that firewall config that @sjeaugey asked you about -- does `[sudo] iptables-save` print any output?

Also, let's experiment with a few tweaks to that client-server code from https://github.com/NVIDIA/nccl-tests/issues/217#issuecomment-2125875092 to get a better feeling what triggers the problem:

1.  Comment out the `shutdown` call in line 78. Any change?
2. Go back to the original version and move the `sleep(5);` from line 31 to line 36 (before the `recv` call). Any change? If not, also add a `sleep(1);` after the `connect` call (line 72 in the original version) and try again.
3. Go back to the original version and add a `sleep(10);` to line 76 (before the `shutdown` call). Any change?
4. Go back to the original version and replace `MSG_DONTWAIT` in the `recv` call in line 39 with `0` (zero). Any change?

**Comment by isaacgerg** [comment] 2024-05-23 15:21
(base) isaac.gerg@highgarden:~$ hostnamectl
   Static hostname: highgarden
         Icon name: computer-server
           Chassis: server
        Machine ID: 078b15e05dfd4619adc5dd6738b608e8
           Boot ID: 7601aa74c4234ecea1bdbcf4ef3e1910
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.15.0-105-generic
      Architecture: x86-64

Anything seem out of the ordinary here?  

Will work out experiments shortly....

**Comment by kiskra-nvidia** [comment] 2024-05-23 15:51
We've got the very same kernel version on a couple of boxes though they seem to be running Ubuntu 22.04.4 LTS? On the 20.04.6 LTS boxes we're running various 5.4.0 kernel variants. Could it be that you are running a kernel version that's not meant for your distro version? Though how that would result in this strange network stack behavior, I have no idea...

Either way, I tried with the same kernel version on Ubuntu 22.04.4 LTS and could not reproduce it there...

**Comment by kiskra-nvidia** [comment] 2024-05-23 18:43
Hey, if you figured out a way to make the C test work, no point in doing the other crazy stuff work -- just try again with NCCL's all_reduce_perf!

**Comment by isaacgerg** [comment] 2024-05-23 18:46
all_reduce_perf now works okay after ESET service restart.

**Comment by sjeaugey** [comment] 2024-05-24 07:04
Thanks for the confirmation @isaacgerg. Feel free to close the issue if the problem is solved. Thanks.

**Closed** 2024-05-24 11:45 UTC

**Comment by isaacgerg** [comment] 2024-05-29 19:52
Quick update:  Disabling ESET's Web Access Protection fixed this issue.

**Comment by HERO-YDX** [comment] 2024-08-01 05:02
> Quick update: Disabling ESET's Web Access Protection fixed this issue.
I think I encountered the same issue as you. Are you using the EEA version? Could you please briefly tell me how to disable ESET's Web Access Protection using commands?

**Comment by isaacgerg** [comment] 2024-08-02 02:25
I am unable to provide you this information.

**Comment by HERO-YDX** [comment] 2024-08-02 02:40
Sorry to bother you. Thank you.
